### PR TITLE
WIP - Variants client projection

### PR DESCRIPTION
**Pull request by nathandunn**

### CODE REVIEW

**Comment by nathandunn** [comment]
- forward (no labels) -> scale vs labelScale: 0.016559668806623868 0.127734375
- reverse (labels) -> scale vs labelScale: 0.016559668806623868 0

Fixed by merging densities.

**Comment by nathandunn** [comment]
@deepakunni3  This is ready to be merged into your branch.

**Comment by nathandunn** [comment]
- [ ] GFF3
  - [ ] Confirm CanvasFeatures
  - [ ] Confirm HTMLFeatures
- [ ] GFF3Tabix
  - [ ] Confirm CanvasFeatures
  - [ ] Confirm HTMLFeatures

**Comment by nathandunn** [comment]
Works in the forward case with 697 objects. In the backwords case we have 1360 objects and none of them render.

For some reason End is being set to "Score" when reversed, so need to fix that..

**Comment by deepakunni3** [comment]
@nathandunn Tested VCF functionality and looks good 👍

**Comment by nathandunn** [comment]
I think you need to merge it because its your branch.  I’ll test them altogether.

**Comment by deepakunni3** [comment]
@nathandunn TravisCI build is broken. But thats because of the progress on GFF3. 

I'll merge it in and we can address that later.

**Comment by nathandunn** [comment]
Okay, I’ll fix the listing error as well. 

Nathan

**Pull request merged**
